language: objective-c

before_install:
    - brew unlink xctool
    - brew update
    - brew install xctool
    - sudo gem install cocoapods
script:
    - xctool clean build test ONLY_ACTIVE_ARCH=NO
    - pod spec lint AeroGear-Push.podspec --verbose


